# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC0u6WaAIqGl6CdY9qSoSOd_2mbM5c9d
"""

!pip install ultralytics -q
!pip install opencv-python -q
!rm -rf /root/.cache/torch/hub/ultralytics_yolov5_master

print("Required packages installed successfully.")

import numpy as np
import cv2
import torch
from google.colab.patches import cv2_imshow
from google.colab import files
print("GPU Available:", torch.cuda.is_available())
!nvidia-smi

yolov5 = torch.hub.load(
    'ultralytics/yolov5',
    'yolov5s',
    pretrained=True,
    trust_repo=True
)

yolov5.conf = 0.30

print("YOLOv5 model loaded successfully.")
print("Confidence threshold set to: 0.30")

uploaded = files.upload()
image_path = list(uploaded.keys())[0]
print("Uploaded image:", image_path)
image = cv2.imread(image_path)
cv2_imshow(image)

results = yolov5(image)

objects = results.xyxyn[0].detach().cpu().numpy()
results.print()
results.show()

classes = yolov5.names

detected_names = []

for obj in objects:
    if obj[-2] > 0.30:
        class_name = classes[int(obj[-1])]
        confidence = obj[-2]
        detected_names.append(class_name)
        print(f"{class_name}: {confidence:.2f}")
print("-" * 30)
print(f"Total detected objects: {len(detected_names)}")
unique_objects = list(set(detected_names))
print(f"Unique object types: {unique_objects}")

output_image = image.copy()

h, w, _ = output_image.shape

objects[:, 0:4] = objects[:, 0:4] * [w, h, w, h]

classes = yolov5.names

for obj in objects:

    if obj[-2] > 0.30:

        tl = obj[0:2].astype('int'), obj[2:4].astype('int')
        br = obj[2:4].astype('int')

        cv2.rectangle(output_image, tuple(tl[0]), tuple(br), (0, 0, 255), 2)

        cv2.putText(
            output_image,
            f'{classes[int(obj[-1])]}: {obj[-2]:.2f}',
            tuple(tl[0] + [-2, -4]),
            cv2.FONT_HERSHEY_DUPLEX,
            0.4,
            (0, 0, 255),
            1
        )

cv2_imshow(output_image)

cv2.imwrite("output_result.png", output_image)

print("Output image saved as output_result.png")

files.download("output_result.png")